name: Test

on: push

jobs:
  test:
    name: Test Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run Jest Tests
      run: yarn test:ci