name: Test

on: pull_request

jobs:
  test:
    name: Test Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run Unit Tests
      run: yarn test:ci --projects tests/unit

    - name: Run Integration Tests
      run: yarn test:ci --projects tests/integration

    - name: Check Code Coverage
      run: yarn test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2

      - name: Build test container
        run: docker-compose build

      - name: Run End-to-End Tests
        run: yarn test:e2e --runInBand --noStackTrace --ci